#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pathlib2
Version  : 2.3.5
Release  : 14
URL      : https://github.com/mcmtroffaes/pathlib2/archive/2.3.5/pathlib2-2.3.5.tar.gz
Source0  : https://github.com/mcmtroffaes/pathlib2/archive/2.3.5/pathlib2-2.3.5.tar.gz
Summary  : Object-oriented filesystem paths
Group    : Development/Tools
License  : MIT
Requires: pathlib2-license = %{version}-%{release}
Requires: pathlib2-python = %{version}-%{release}
Requires: pathlib2-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
The `old pathlib <https://bitbucket.org/pitrou/pathlib>`_
module on bitbucket is in bugfix-only mode.
The goal of pathlib2 is to provide a backport of
`standard pathlib <http://docs.python.org/dev/library/pathlib.html>`_
module which tracks the standard library module,
so all the newest features of the standard pathlib can be
used also on older Python versions.

Download
--------

Standalone releases are available on PyPI:
http://pypi.python.org/pypi/pathlib2/

Development
-----------

The main development takes place in the Python standard library: see
the `Python developer's guide <http://docs.python.org/devguide/>`_.
In particular, new features should be submitted to the
`Python bug tracker <http://bugs.python.org/>`_.

Issues that occur in this backport, but that do not occur not in the
standard Python pathlib module can be submitted on
the `pathlib2 bug tracker <https://github.com/mcmtroffaes/pathlib2/issues>`_.

Documentation
-------------

Refer to the
`standard pathlib <http://docs.python.org/dev/library/pathlib.html>`_
documentation.

Known Issues
------------

For historic reasons, pathlib2 still uses bytes to represent file paths internally.
Unfortunately, on Windows with Python 2.7, the file system encoder (``mcbs``)
has only poor support for non-ascii characters,
and can silently replace non-ascii characters without warning.
For example, ``u'тест'.encode(sys.getfilesystemencoding())`` results in ``????``
which is obviously completely useless.

Therefore, on Windows with Python 2.7, until this problem is fixed upstream,
unfortunately you cannot rely on pathlib2 to support the full unicode range for filenames.
See `issue #56 <https://github.com/mcmtroffaes/pathlib2/issues/56>`_ for more details.

.. |travis| image:: https://travis-ci.org/mcmtroffaes/pathlib2.png?branch=develop
    :target: https://travis-ci.org/mcmtroffaes/pathlib2
    :alt: travis-ci

.. |appveyor| image:: https://ci.appveyor.com/api/projects/status/baddx3rpet2wyi2c?svg=true
    :target: https://ci.appveyor.com/project/mcmtroffaes/pathlib2
    :alt: appveyor

.. |codecov| image:: https://codecov.io/gh/mcmtroffaes/pathlib2/branch/develop/graph/badge.svg
    :target: https://codecov.io/gh/mcmtroffaes/pathlib2
    :alt: codecov

%package license
Summary: license components for the pathlib2 package.
Group: Default

%description license
license components for the pathlib2 package.


%package python
Summary: python components for the pathlib2 package.
Group: Default
Requires: pathlib2-python3 = %{version}-%{release}

%description python
python components for the pathlib2 package.


%package python3
Summary: python3 components for the pathlib2 package.
Group: Default
Requires: python3-core
Provides: pypi(pathlib2)

%description python3
python3 components for the pathlib2 package.


%prep
%setup -q -n pathlib2-2.3.5
cd %{_builddir}/pathlib2-2.3.5

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583201160
# -Werror is for werrorists
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$CFLAGS -fno-lto "
export FFLAGS="$CFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pathlib2
cp %{_builddir}/pathlib2-2.3.5/LICENSE.rst %{buildroot}/usr/share/package-licenses/pathlib2/cb5565585466f49a5bb169410c92e31b3872a30c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pathlib2/cb5565585466f49a5bb169410c92e31b3872a30c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
