#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pathlib2
Version  : 2.3.6
Release  : 26
URL      : https://github.com/mcmtroffaes/pathlib2/archive/2.3.6/pathlib2-2.3.6.tar.gz
Source0  : https://github.com/mcmtroffaes/pathlib2/archive/2.3.6/pathlib2-2.3.6.tar.gz
Summary  : Object-oriented filesystem paths
Group    : Development/Tools
License  : MIT
Requires: pathlib2-license = %{version}-%{release}
Requires: pathlib2-python = %{version}-%{release}
Requires: pathlib2-python3 = %{version}-%{release}
Requires: six
BuildRequires : buildreq-distutils3
BuildRequires : six

%description
pathlib2
========
|github| |appveyor| |codecov|
Fork of pathlib aiming to support the full stdlib Python API.

%package license
Summary: license components for the pathlib2 package.
Group: Default

%description license
license components for the pathlib2 package.


%package python
Summary: python components for the pathlib2 package.
Group: Default
Requires: pathlib2-python3 = %{version}-%{release}

%description python
python components for the pathlib2 package.


%package python3
Summary: python3 components for the pathlib2 package.
Group: Default
Requires: python3-core
Provides: pypi(pathlib2)
Requires: pypi(six)

%description python3
python3 components for the pathlib2 package.


%prep
%setup -q -n pathlib2-2.3.6
cd %{_builddir}/pathlib2-2.3.6

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1631314203
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/pathlib2
cp %{_builddir}/pathlib2-2.3.6/LICENSE.rst %{buildroot}/usr/share/package-licenses/pathlib2/cb5565585466f49a5bb169410c92e31b3872a30c
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/pathlib2/cb5565585466f49a5bb169410c92e31b3872a30c

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
